"use client"

import { Users, Calendar, Trophy, Star, X } from "lucide-react"
import { useRouter } from "next/navigation"
import { useState, useEffect } from "react"
import { createClient } from "@/lib/supabase/client"

interface Member {
    id: string;
    avatar_url: string | null;
    full_name: string;
    role?: 'admin' | 'member' | string;
}

interface CommunityStatsProps {
    membersCount: number;
    activeEventsCount?: number;
    totalEventsCount?: number;
    rating?: number;
    community_id: string;
}

// Helper component to display member avatar
function MemberAvatar({ member }: { member: Member }) {
    if (member.avatar_url) {
        return (
            <img
                src={member.avatar_url}
                alt={member.full_name}
                className="w-full h-full object-cover"
            />
        )
    }

    // Fallback: show initials
    const initials = member.full_name
        .split(' ')
        .map(n => n[0])
        .join('')
        .toUpperCase()
        .slice(0, 2)

    // Generate a consistent color based on the name
    const colors = ['bg-blue-500', 'bg-green-500', 'bg-purple-500', 'bg-pink-500', 'bg-orange-500']
    const colorIndex = member.full_name.charCodeAt(0) % colors.length

    return (
        <div className={`w-full h-full ${colors[colorIndex]} flex items-center justify-center text-white text-xs font-bold`}>
            {initials}
        </div>
    )
}

// Helper component to display member grid
function MemberGrid({ members, maxDisplay = 12, gapX = 1, gapY = 1 }: { members: Member[], maxDisplay?: number, gapX?: number, gapY?: number }) {
    const displayMembers = members.slice(0, maxDisplay)
    const remainingCount = Math.max(0, members.length - maxDisplay)

    // Using inline style to ensure gap is applied correctly since dynamic tailwind classes 
    // might not be generated by the compiler.
    const gridStyle = {
        columnGap: `${gapX * 0.07}rem`,
        rowGap: `${gapY * 0.25}rem`
    }

    return (
        <div className="grid grid-cols-4" style={gridStyle}>
            {displayMembers.map(member => (
                <div key={member.id} className="w-8 h-8 rounded-full border-2 border-black overflow-hidden bg-gray-200">
                    <MemberAvatar member={member} />
                </div>
            ))}
            {remainingCount > 0 && (
                <div className="w-8 h-8 rounded-full border-2 border-black overflow-hidden bg-black flex items-center justify-center">
                    <span className="text-white text-[10px] font-bold">+{remainingCount}</span>
                </div>
            )}
        </div>
    )
}

export function CommunityStats({
    membersCount,
    activeEventsCount = 0,
    totalEventsCount,
    rating = 4.9,
    community_id
}: CommunityStatsProps) {
    const router = useRouter()
    const supabase = createClient()
    const safeActiveEvents = Math.max(activeEventsCount, 0)
    const safeTotalEvents = Math.max(totalEventsCount ?? safeActiveEvents, safeActiveEvents, 0)
    const activityBarPercent = safeTotalEvents > 0
        ? Math.min((safeActiveEvents / safeTotalEvents) * 100, 100)
        : 0

    const [members, setMembers] = useState<Member[]>([])
    const [allMembers, setAllMembers] = useState<Member[]>([])
    const [totalMembersCount, setTotalMembersCount] = useState(membersCount)
    const [newMembersCount, setNewMembersCount] = useState(0)
    const [isLoading, setIsLoading] = useState(true)
    const [isMembersModalOpen, setIsMembersModalOpen] = useState(false)
    const [isMembersModalLoading, setIsMembersModalLoading] = useState(false)
    const [membersModalError, setMembersModalError] = useState<string | null>(null)

    // Sync totalMembersCount when prop changes (e.g. after join/leave action)
    useEffect(() => {
        setTotalMembersCount(membersCount)
    }, [membersCount])

    useEffect(() => {
        const fetchMembers = async () => {
            try {
                if (members.length === 0) setIsLoading(true)

                // First, get the total count
                const { count, error: countError } = await supabase
                    .from('community_members')
                    .select('*', { count: 'exact', head: true })
                    .eq('community_id', community_id)
                    .eq('status', 'approved')

                if (countError) throw countError

                // Update the total count - keep in sync with DB
                setTotalMembersCount(count || 0)

                // Get new members count (last 7 days)
                const sevenDaysAgo = new Date()
                sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)

                const { count: newCount, error: newCountError } = await supabase
                    .from('community_members')
                    .select('*', { count: 'exact', head: true })
                    .eq('community_id', community_id)
                    .eq('status', 'approved')
                    .gte('joined_at', sevenDaysAgo.toISOString())

                if (!newCountError) {
                    setNewMembersCount(newCount || 0)
                }

                // Then fetch the member details
                const { data, error } = await supabase
                    .from('community_members')
                    .select(`
                        id,
                        user_id,
                        role,
                        users (
                            id,
                            avatar_url,
                            full_name
                        )
                    `)
                    .eq('community_id', community_id)
                    .eq('status', 'approved')
                    .order('joined_at', { ascending: false })
                    .limit(13) // Fetch 13 to know if there are more than 12

                if (error) throw error

                // Transform the data to flat structure
                const transformedMembers: Member[] = (data || []).map((member: any) => ({
                    id: member.users?.id || member.user_id,
                    avatar_url: member.users?.avatar_url || null,
                    full_name: member.users?.full_name || 'Unknown Member',
                    role: member.role
                }))

                setMembers(transformedMembers)
            } catch (error) {
                console.error('Error fetching members:', error)
            } finally {
                setIsLoading(false)
            }
        }

        fetchMembers()
    }, [community_id, supabase, membersCount])

    useEffect(() => {
        if (!isMembersModalOpen) return

        let isActive = true

        const fetchAllMembers = async () => {
            try {
                setIsMembersModalLoading(true)
                setMembersModalError(null)

                const { data, error } = await supabase
                    .from('community_members')
                    .select(`
                        id,
                        user_id,
                        role,
                        users (
                            id,
                            avatar_url,
                            full_name
                        )
                    `)
                    .eq('community_id', community_id)
                    .eq('status', 'approved')
                    .order('joined_at', { ascending: false })

                if (error) throw error

                const transformedMembers: Member[] = (data || []).map((member: any) => ({
                    id: member.users?.id || member.user_id,
                    avatar_url: member.users?.avatar_url || null,
                    full_name: member.users?.full_name || 'Unknown Member',
                    role: member.role
                }))

                if (!isActive) return
                setAllMembers(transformedMembers)
            } catch (error) {
                console.error('Error fetching all members:', error)
                if (isActive) setMembersModalError("Gagal memuat daftar member.")
            } finally {
                if (isActive) setIsMembersModalLoading(false)
            }
        }

        fetchAllMembers()

        return () => {
            isActive = false
        }
    }, [isMembersModalOpen, community_id, supabase])

    const handleRatingClick = () => {
        router.push(`/communities/${community_id}/reviews`)
    }

    return (
        <>
            <div className="grid grid-cols-2 lg:grid-cols-1 gap-3 mb-8">
            {/* Members Card - Left Column spanning full height of this row */}
            <div className="bg-white border-3 border-black shadow-hard rounded-xl p-5 flex flex-col justify-between relative overflow-hidden h-full min-h-[180px]">
                {/* Divider Line - Horizontal di mobile, Vertical di desktop */}
                <div className="absolute left-0 right-0 top-[22%] -translate-y-1/2 h-[3px] lg:left-[30%] lg:top-0 lg:bottom-0 lg:-translate-x-1/2 lg:translate-y-0 lg:w-[3px] lg:h-auto bg-black"></div>

                <div className="flex justify-between items-start mb-2 relative z-10">
                    <Users className="text-black w-8 h-8" />
                    <button
                        type="button"
                        onClick={() => setIsMembersModalOpen(true)}
                        className="bg-black text-white text-[10px] font-black px-2 py-1 uppercase tracking-widest hover:bg-white hover:text-black transition-colors border-2 border-black"
                        aria-label="Lihat daftar member"
                    >
                        Members
                    </button>
                </div>

                {/* Layout dengan 2 kolom - Desktop Only */}
                <div className="hidden lg:flex gap-0 items-stretch flex-1 relative z-10">
                    {/* Left Section - Stats */}
                    <div className="flex flex-col justify-between flex-1">
                        <div className="mt-2">
                            <span className="text-6xl font-black block tracking-tighter text-black leading-none">{totalMembersCount}</span>
                            <span className="text-xs font-bold text-green-600 uppercase tracking-tight -ml-1">+{newMembersCount} this week</span>
                        </div>
                    </div>

                    {/* Right Section - Member Profile Pictures */}
                    <div className="flex-1 flex items-end -ml-28">
                        {!isLoading && members.length > 0 && (
                            <MemberGrid members={members} maxDisplay={12} gapX={32} gapY={2} />
                        )}
                    </div>
                </div>

                {/* Mobile Layout - Custom Positioning */}
                <div className="lg:hidden flex-1 relative z-10">
                    {/* Angka Total Members - Kiri Bawah */}
                    <div className="absolute bottom-0 left-0">
                        <span className="text-5xl font-black block tracking-tighter text-black leading-none">{totalMembersCount}</span>
                    </div>

                    {/* +12 this week - Kanan Bawah */}
                    <div className="absolute bottom-0 right-0">
                        <span className="text-xs font-bold text-green-600 uppercase tracking-tight">+{newMembersCount} this week</span>
                    </div>

                    {/* Member Profile Pictures - Kiri Atas dekat garis */}
                    <div className="absolute top-[10%] -left-1">
                        {!isLoading && members.length > 0 && (
                            <MemberGrid members={members} maxDisplay={12} gapX={2} gapY={2} />
                        )}
                    </div>
                </div>
            </div>

            {/* Right Column - Stacked Cards */}
            <div className="flex flex-col gap-3">
                {/* Activities Card */}
                <div className="bg-neo-blue border-3 border-black shadow-hard rounded-xl p-5 text-white relative flex-1 flex flex-col justify-between">
                    <div className="flex justify-between items-start">
                        <h3 className="text-sm font-black uppercase tracking-widest">Activities</h3>
                        <Calendar className="w-6 h-6 stroke-[3px]" />
                    </div>
                    <div>
                        <span className="text-5xl font-black tracking-tighter leading-none">{activeEventsCount}</span>
                    </div>
                    <div
                        className="w-full bg-black/20 h-3 rounded-full overflow-hidden mt-2 border border-black/10"
                        role="progressbar"
                        aria-valuemin={0}
                        aria-valuemax={safeTotalEvents}
                        aria-valuenow={safeActiveEvents}
                        aria-label={`Active activities: ${safeActiveEvents} of ${safeTotalEvents}`}
                    >
                        <div className="bg-primary h-full border-r-2 border-black" style={{ width: `${activityBarPercent}%` }}></div>
                    </div>
                </div>

                {/* Rating Card */}
                <div
                    onClick={handleRatingClick}
                    className="bg-primary border-3 border-black shadow-hard rounded-xl p-5 text-black relative flex-1 flex flex-col justify-between cursor-pointer active:translate-y-[2px] active:shadow-neo-sm transition-all hover:shadow-neo-lg"
                >
                    <div className="flex justify-between items-start">
                        <h3 className="text-sm font-black uppercase tracking-widest">Rating</h3>
                        <Trophy className="w-6 h-6 stroke-[3px]" />
                    </div>
                    <div className="flex items-end gap-2 mt-1">
                        <span className="text-5xl font-black tracking-tighter leading-none">{rating}</span>
                        <div className="flex pb-2 gap-0.5">
                            {[...Array(4)].map((_, i) => (
                                <Star key={i} className="w-4 h-4 fill-black text-black" />
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            </div>
            {isMembersModalOpen && (
                <div className="fixed inset-0 z-50">
                    <div
                        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
                        onClick={() => setIsMembersModalOpen(false)}
                    />
                    <div className="absolute inset-0 flex items-center justify-center p-4">
                        <div className="bg-white w-full max-w-lg max-h-[80vh] rounded-3xl border-3 border-black shadow-hard overflow-hidden flex flex-col">
                            <div className="p-5 border-b-3 border-black flex items-center justify-between bg-neo-yellow">
                                <div>
                                    <h3 className="text-lg font-black uppercase tracking-wider">Members</h3>
                                    <p className="text-xs text-gray-700 font-medium">
                                        {totalMembersCount} member{totalMembersCount === 1 ? "" : "s"}
                                    </p>
                                </div>
                                <button
                                    type="button"
                                    onClick={() => setIsMembersModalOpen(false)}
                                    className="w-9 h-9 flex items-center justify-center bg-white border-2 border-black rounded-full hover:bg-black hover:text-white transition-colors"
                                    aria-label="Close members list"
                                >
                                    <X className="w-4 h-4 stroke-[3px]" />
                                </button>
                            </div>
                            <div className="p-5 overflow-y-auto">
                                {isMembersModalLoading ? (
                                    <div className="text-center py-10 text-gray-500 font-medium">Loading members...</div>
                                ) : membersModalError ? (
                                    <div className="text-center py-10 text-red-500 font-medium">{membersModalError}</div>
                                ) : allMembers.length === 0 ? (
                                    <div className="text-center py-10 text-gray-500 font-medium">Belum ada member.</div>
                                ) : (
                                    <ul className="space-y-2">
                                        {allMembers.map(member => (
                                            <li key={member.id} className="flex items-center gap-3 p-3 border-2 border-black/10 rounded-xl">
                                                <div className="w-10 h-10 rounded-full border-2 border-black overflow-hidden bg-gray-200">
                                                    <MemberAvatar member={member} />
                                                </div>
                                                <div className="flex-1 flex items-center justify-between gap-2">
                                                    <div className="font-bold text-sm">{member.full_name}</div>
                                                    {member.role === 'admin' && (
                                                        <span className="text-[10px] font-black uppercase tracking-widest bg-black text-white px-2 py-1 rounded-full border border-black">
                                                            Admin
                                                        </span>
                                                    )}
                                                </div>
                                            </li>
                                        ))}
                                    </ul>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </>
    )
}
